### ISSUE TITLE
[New Backend] How to generate "***RegisterClassDecl.hs", "***RegisterDecl.hs", "***ResourceDecl.hs", "***-remat.yaml" and "***-manual.yaml"?

### ISSUE THREAD

**Issue by DKXXXL** [unison-code/unison#36]
For example, how do you generate HexagonRegisterClassDecl, HexagonRegisterDecl and HexagonResourceDecl?

The files are not autogenerated by specsgen while I don't believe they are manually written. 
I was facing two possible options:
1. use "llvm-tblgen -print-enums -class=Registers/RegisterClass" to get all the register name;
2. try to build the project and see what are claimed to be data constructors by the auto-generated files

The output of those two options don't coincide.

I was sticking to 1 at first but to pass the compilation I have to use (union) the 2 as well.
However, what is the correct way?

**Comment by robcasloz** [comment]
As you point out, these files cannot be currently auto-generated with `specsgen`.

The register classes in the auto-generated files are the union of what you get with option 1 and some additional register classes introduced by `specsgen` to represent memory and rematerialization [1] registers. Hence I would say option 2 is the correct way.

Registers and resources can be derived quite mechanically from the corresponding `*RegisterInfo.td` and `*Schedule*.td` TableGen files in the LLVM source.

We will describe this process in the Unison manual. I will leave this issue open until then.

[1] https://arxiv.org/pdf/1804.02452.pdf (Section 4.5).

**Comment by DKXXXL** [comment]
About Hexagon-remat.yaml and Hexagon-manual.yaml, how are they generated? Are they optional or mandatory?
I have checked the backend for Hexagon, ARM and MIPS, the "fromCopy" requires "handling rematerization copies" in there pattern matching; but the guard _isDematInstr_ and _isRematInstr_ both require _rematVersion_ , which is defined using some instructions I currently don't have (with suffix "demat", "remat")

In my opinion, "fromCopy" is trying to replacing the copy instruction with appropriate substitution.
I have tried to let the unison run on the private backend (the factorial example) but at the end there were a lot of moving instructions (I think are redundant). I suspect it is the issue of _fromCopy_? Currently my _fromCopy_ will just transform Copy Operation into Linear Natural operation.

**Comment by DKXXXL** [comment]
It turns out not to be the fault of fromCopy... 
I didn't have ***-manual.yaml and didn't have the pseudo instructions of type "copy". I think that is the issue those "move" instruction are not deleted at the end.

**Comment by robcasloz** [comment]
Hi, your reasoning is correct: the expected workflow is that the targets extends the function with optional copies (via the `copies` target function) where for each introduced copy instruction `i`, `instructionType i = CopyInstructionType` must hold. These pseudo-instructions must be defined manually (typically in `*-manual.yaml`), and are usually abstractions of real processor instructions (register-to-register moves, stores, loads, inter-bank copies, etc.). The function `fromCopy` is responsible for transforming such copy instructions into their real corresponding instructions.

Regarding rematerialization copies, they are intended to be optional so I would skip them in the first version of the target description, for simplicity (just define `rematInstrs i = Nothing` for all `i` and no rematerialization copy should show up in `fromCopy`). Rematerialization copies must be defined in yet another YAML file (typically in `*-remat.yaml`) which must be passed to `specsgen` using the argument `--rematfile=*-remat.yaml`. This is because `specsgen` has a special processing of these copies where each entry `i` in the YAML file is specialized into `i_source`, `i_demat`, and `i_remat` versions to support our rematerialization model.
