### ISSUE TITLE
[New Target] What are "tAddPro/Epilogue", "tPre/PostProcess", "tTransform" supposed to do?

### ISSUE THREAD

**Issue by DKXXXL** [unison-code/unison#37]
The comments  on those 5 functions are too vague, before I dive into the source code of Hexagon/ARM/MIPS, do you have any suggestion that can make them simple to understand? 
I currently simply put them into identity or just empty list...

**Comment by robcasloz** [comment]
Actually, the reason why the comments on these functions are vague is because they are really target-dependent. You can see them as "target-specific hooks" (in LLVM terminology) that allow you to perform arbitrary transformations to the function at different points of the Unison toolchain and on different program representations. You can have a look at this table: https://github.com/unison-code/unison/blob/3478382bc774e179337d2e8cafd46fe368c1497f/src/unison/src/Unison/Target/API.hs#L214 to see the points at which each of these functions is invoked.

Having said this, `tAddPro/Epilogue` are typically used to introduce stack management instructions such as increments and decrements of the stack pointer. They are somewhat akin to LLVM's `emitPrologue` and `emitEpilogue` methods in https://llvm.org/doxygen/classllvm_1_1TargetFrameLowering.html.
