### ISSUE TITLE
[New Target] The input/output format MIR of unison and the integration with LLVM

### ISSUE THREAD

**Issue by DKXXXL** [unison-code/unison#38]
Currently I am using a private LLVM4 because that is where the new target located on.
But I noticed that when I hijacked the mir from the llc (of the private LLVM4), "-stop-after" the "Live analysis"...... (I don't know which stage of MIR to choose so I choose that because that is an SSA and has livein information)

1. the format is a little off from the expected input of unison. Unison needs block frequency info; and to enforce the calling convention there has to be the "liveouts" declaration otherwise Unison will use callee saved register as return register. I suspect llvm-unison-driver did something on that? I currently change these manually, but is it possible that without large modification on the private LLVM4 I can get those format change?
2. there is "implicit-def, implicit" operand on some instructions which are ignored by the unison but at the end I need to add them back to the  "*.unison.mir" so that llc can parse them again. I use "llc -run-after=llvmdebugvalues" so that emission from "*.unison.mir" to "*.asm" is possible. Is there other way that possible to transform "*.unison.mir" to "*.asm"? If not, should I worry about the disappear of the implicit operands?
3. to find out the real pass stage (after which llc can give as input to the unison), I look into all the IR dump by llvm-unison-driver. To my surprise, the unison driver choose to take in after the final pass "live debug analysis". But the format at that stage is far from that described in the manual. There is no phi instruction, not an SSA, and there are even bundles in it (for hexagon). Did I misunderstand something? And ultimately, after which pass for llc is the proper MachineIR as the input to the unison?

**Comment by robcasloz** [comment]
Hi @DKXXXL, thanks for the questions!

1. That is correct, Unison assumes that its input is "MIR in Unison style" as generated by the LLVM/Unison driver. The Unison-style MIR  is essentially LLVM's MIR extended with 1) additional LLVM analysis results (basic block frequency estimation and alias information, see https://github.com/unison-code/llvm/blob/master/lib/CodeGen/UnisonMIRPrepare.cpp) and 2) explicit liveness and return information. The MIR is also simplified in a couple of aspects, see https://github.com/unison-code/llvm/blob/master/lib/CodeGen/MIRPrinter.cpp (look for the flag `UnisonMIR`).
We have currently two alternative LLVM/Unison driver implementations: a "standard" one in https://github.com/unison-code/llvm/tree/release_38-unison for LLVM 3.8 and an experimental one in https://github.com/unison-code/llvm/tree/master that is meant to become the standard one. You will have to either port the LLVM 3.8 version or backport the "master" version. The structure of these drivers is quite different: in the standard one, `llc` acts as a driver of Unison. This makes it quite intrusive and less flexible (but version-wise it is closer to LLVM4). In the experimental one, there is a `llc-unison` script that acts as a driver of both `llc` and Unison. This makes it much less intrusive (the only changes are for emitting Unison-style MIR) and more flexible (it is easier to select the exact exit and entry points to `llc`), but assumes that `llc` is able to emit and parse MIR at any point, which was not fully supported in LLVM 3.8 (I do not know about LLVM4). If LLVM4 supports that, I would recommend backporting the experimental driver.

2. Your way of transforming `.unison.mir` to `.asm` is correct. A target is expected to include all those implicit operands before MIR emission and Unison has support for that, see e.g. https://github.com/unison-code/unison/blob/3478382bc774e179337d2e8cafd46fe368c1497f/src/unison/src/Unison/Target/Hexagon.hs#L537
Since listing implicit registers seems to be a requirement of LLVM and not of individual targets, we should probably make Unison do this to all targets by default.

3. Unison takes two MIR files as input:
- a function for which register allocation and instruction scheduling is to be performed (`.mir`) and
- a function where LLVM has already performed register allocation and instruction scheduling (`.asm.mir`) as a starting point for the optimization algorithm (so that the solver concentrates on finding better solutions than LLVM's).
See Chapter 3 in https://unison-code.github.io/doc/manual.pdf for more info.
