### ISSUE TITLE
Query regarding the selection of Gecode solver

### ISSUE THREAD

**Issue by utkarshyen** [unison-code/unison#47]
Hello @robcasloz,

I have checked the Minizinc Challenge 2019, where **or-tools** have outperformed.
Downloaded the testcases and saw unison.mzn model file in code generation.

With those same testcase and unison.mzn file, below are the results for Gecode and or-tools solver.
**Gecode - Runs.
Or-tools - Error.**

However, I have replaced the unizon.mzn model file from latest unison source. I could see many constrains are added. And below are the results,
**Gecode - Runs.
Or-tools - Runs.**
And please note, or-tools takes less time compare to Gecode.

However, when I tried executing some Image processing samples/problems with unison (Gecode and or-tools solvers).
**Gecode - More than an hour (Might be in infinite loop)
Or-tools - less than an hour.**

Got few queries,
1. Is different solvers uses different programming constrains?
2. Why Unison selected Gecode as a primary solver?
3. What benchmark criteria used by Unison? 

Regards,
UT

**Comment by utkarshyen** [comment]
Even for other problem statements or-tools scores more.
Stating or-tools performed well compared to gecode.

@robcasloz  Can you please put some light on why unison chose Gecode as a primary solver? Is there anything related to code-generation.

Regards,
UT

**Comment by robcasloz** [comment]
Hi, we use Gecode for the decomposition-based solver (see [the TOPLAS paper](https://arxiv.org/abs/1804.02452)) because Gecode provides full flexibility for designing custom decompositions, search strategies, etc.

For the MiniZinc-based solver, we have actually experimented more with Chuffed than with Gecode as a MiniZinc back-end. Chuffed has similar characteristics to OR-Tools in that both use a hybrid CP/SAT technique to solve the problems.

Regarding the benchmark criteria, again please see [the TOPLAS paper](https://arxiv.org/abs/1804.02452) (Section 11) for a thorough discussion.
