### ISSUE TITLE
Question about post-RA pipeline

### ISSUE THREAD

**Issue by yugr** [unison-code/unison#62]
It seems that currently Unison compilation replaces all post-RA passes of LLVM pipeline. Relevant passes e.g. pseudo-expansions and frame lowering are implemented manually in backend's postProcess callbacks.

This approach has some disadvantages:
1) relevant lowering code needs to be duplicated from LLVM backend
2) LLVM post-RA optimizations (e.g. Control Flow Optimizer, Tail Duplication, backend-specific peepholes) are not applied
3) `maxf` bound may be imprecise because it will compare unlowered Unison code against fully lowered LLVM code

Have alternatives to current solution been considered e.g. calculating `maxf` from post-RA MIR (rather than final MIR) or running the rest of post-RA pipeline over Unison code?

**Comment by robcasloz** [comment]
Hi @yugr, thanks for your interest!

> Relevant passes e.g. pseudo-expansions and frame lowering are implemented manually in backend's postProcess callbacks.

Note that this depends on the interaction between each individual transformation and the problem Unison tries to solve. For example, the best way to expand a pseudo-instruction might depend on register allocation and instruction scheduling decisions. In this case, it would be an advantage to model the expansion as part of the Unison problem, e.g. using alternative instructions. In the context of frame lowering, knowing whether spill slots will be required might affect how or even whether the frame is managed, and Unison might exploit this to generate better code (see Sect. 9, paragraph _Stack frame elimination_ in the [TOPLAS 2019 paper](https://arxiv.org/abs/1804.02452)). Some other transformations might be totally orthogonal and best moved before or after Unison.

> relevant lowering code needs to be duplicated from LLVM backend

This is clearly an issue, in particular for frame lowering transformations which are tedious to duplicate on the Unison side.

> maxf bound may be imprecise because it will compare unlowered Unison code against fully lowered LLVM code

In our experiments, we controlled this by simply disabling post-RA optimizations on both sides (see TOPLAS 2019, Section 11.1).

> Have alternatives to current solution been considered e.g. calculating maxf from post-RA MIR (rather than final MIR) or running the rest of post-RA pipeline over Unison code?

In the experiments, we circumvented this issue by simply disabling post-RA optimizations (so that post-RA MIR = final MIR), but of course in a more practical scenario one would want to do as you suggest (calculating `maxf` from post-RA MIR and then running the rest of post-RA pipeline over Unison code). In general, I don't see any fundamental reason why clearly orthogonal transformations like tail duplication, block placement, etc. cannot be applied to Unison-generated MIR. For back-end-specific peepholes, it could often be the case that there is some advantage in integrating with Unison, but this needs to be evaluated on a case-by-case basis.

Note that the LLVM/Unison driver was developed around the Hexagon back-end, which includes a late VLIW bundling pass. I seem to remember that many of the post-RA passes run before it and assume register-allocated, non-bundled code, and this was one particular difficulty for us since such form is never available when using Unison, by its very integrated nature. This might be easier for more conventional architectures without instruction bundles.

Hope this helped!

Cheers,

Roberto
